#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 name1 [name2 ...]"
  exit 1
fi

REMOTE_HOST="host"
REMOTE_FILE="*.csv"
REMOTE_PATH="~"

REMOTE_FILE_PARENT="${REMOTE_FILE%/*}"
if [[ "$REMOTE_FILE" == "$REMOTE_FILE_PARENT" ]] 
then
    REMOTE_FILE_PARENT=""
fi

for dir in "$@"
do
  remote_path="${REMOTE_HOST}:${REMOTE_PATH}/${dir}/${REMOTE_FILE}"
  local_dir="./${dir}/${REMOTE_FILE_PARENT}"

  mkdir -p -- "${dir}"
  scp -r -- "$remote_path" "$local_dir/"
done
